version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/packages/registry"
    update_schedule: "live"
  - package_manager: "javascript"
    directory: "/packages/loom"
    update_schedule: "live"
  - package_manager: "javascript"
    directory: "/docs"
    update_schedule: "live"
